package com.swmansion.kmpmaps

/** Categories of points of interest (POI) for Apple Maps. */
public enum class AppleMapsPointOfInterestCategory {
    AIRPORT,
    AMUSEMENT_PARK,
    ANIMAL_SERVICE,
    AQUARIUM,
    ATM,
    AUTOMOTIVE_REPAIR,
    BAKERY,
    BANK,
    BASEBALL,
    BASKETBALL,
    BEACH,
    BEAUTY,
    BOWLING,
    BREWERY,
    CAFE,
    CAMPGROUND,
    CAR_RENTAL,
    CASTLE,
    CONVENTION_CENTER,
    DISTILLERY,
    EV_CHARGER,
    FAIRGROUND,
    FIRE_STATION,
    FISHING,
    FITNESS_CENTER,
    FOOD_MARKET,
    FORTRESS,
    GAS_STATION,
    GO_KART,
    GOLF,
    HIKING,
    HOSPITAL,
    HOTEL,
    KAYAKING,
    LANDMARK,
    LAUNDRY,
    LIBRARY,
    MAILBOX,
    MARINA,
    MINI_GOLF,
    MOVIE_THEATER,
    MUSEUM,
    MUSIC_VENUE,
    NATIONAL_MONUMENT,
    NATIONAL_PARK,
    NIGHTLIFE,
    PARK,
    PARKING,
    PHARMACY,
    PLANETARIUM,
    POLICE,
    POST_OFFICE,
    PUBLIC_TRANSPORT,
    RESTAURANT,
    RESTROOM,
    ROCK_CLIMBING,
    RV_PARK,
    SCHOOL,
    SKATE_PARK,
    SKATING,
    SKIING,
    SOCCER,
    SPA,
    STADIUM,
    STORE,
    SURFING,
    SWIMMING,
    TENNIS,
    THEATER,
    UNIVERSITY,
    VOLLEYBALL,
    WINERY,
    ZOO,
}

/** Types of map display modes. */
public enum class MapType {
    HYBRID,
    NORMAL,
    SATELLITE,
    TERRAIN,
}

public enum class MapPlatform {
    GOOGLE_MAPS,
    NATIVE,
}
