name: Build
on:
  merge_group:
  pull_request:
  push:
    branches: [main]
jobs:
  build:
    runs-on: [self-hosted, macOS, ARM64]
    steps:
      - uses: actions/checkout@v5
      - run: java -version
