name: Check formatting
on:
  merge_group:
  pull_request:
  push:
    branches: [main]
jobs:
  check-formatting:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v5
      - run: ktfmt --dry-run --kotlinlang-style --set-exit-if-changed .
